# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

#[[main]]
#  name = "Projects"
#  url = "projects"
#  weight = 20

[[main]]
  name = "Courses"
  url = "courses"
  weight = 30

[[main]]
  name = "Office Hours"
  url = "office_hours"
  weight = 55

# Link to a PDF of your resume/CV from the menu.
[[main]]
  name = "CV"
  url = "files/Brian_Plancher_CV.pdf"
  weight = 60

[[main]]
  name = "Publications"
  url = "publication"
  weight = 11

[[main]]
  name = "AÂ²R Lab Research"
  url = "https://a2r-lab.org"
  weight = 10

[[main]]
  name = "Dartmouth CS"
  url = "https://web.cs.dartmouth.edu/"
  weight = 80

[[main]]
  name = "Dartmouth AI"
  url = "https://ai.dartmouth.edu/"
  weight = 85